[build]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
